# Generated by Django 5.1.1 on 2024-09-25 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Age', models.IntegerField()),
                ('Username', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=50)),
                ('Password', models.CharField(max_length=50)),
                ('Phone', models.IntegerField()),
                ('Catogory', models.CharField(max_length=50)),
                ('Address', models.TextField(blank=True, null=True)),
                ('Department', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
