# Generated by Django 5.1.1 on 2024-09-26 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_1', '0004_alter_registration_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='Age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='Age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patients',
            name='Age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='Age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
