# Generated by Django 5.1.1 on 2024-09-26 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_1', '0005_alter_booking_age_alter_doctor_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='Password',
            field=models.CharField(max_length=200),
        ),
    ]
