# Generated by Django 5.1.1 on 2024-09-26 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_1', '0006_alter_registration_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='Password',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='Password',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='patients',
            name='Password',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='staff',
            name='Password',
            field=models.CharField(max_length=200),
        ),
    ]
