# Generated by Django 5.1.1 on 2024-09-26 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_1', '0007_alter_booking_password_alter_doctor_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='Phone',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='Phone',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='patients',
            name='Phone',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='registration',
            name='Phone',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='staff',
            name='Phone',
            field=models.TextField(),
        ),
    ]
