# Generated by Django 5.1.1 on 2024-09-26 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_1', '0008_alter_booking_phone_alter_doctor_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='Catogory',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='Catogory',
        ),
        migrations.RemoveField(
            model_name='patients',
            name='Catogory',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='Catogory',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='Catogory',
        ),
        migrations.AddField(
            model_name='booking',
            name='Catagory',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='Catagory',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patients',
            name='Catagory',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='Catagory',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='Catagory',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
