# Generated by Django 5.1.1 on 2024-10-09 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_1', '0009_remove_booking_catogory_remove_doctor_catogory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='Tocken',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
